#version: '3'
services:
  redpanda1:
    image: docker.vectorized.io/vectorized/redpanda:v21.7.6
    container_name: redpanda1
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda1:29092,OUTSIDE://localhost:9092
      - --advertise-rpc-addr redpanda1:33145
      - --rpc-addr redpanda1:33145
    ports:
      - '9092:9092'
      - '29092:29092'
      - '9644:9644'
    expose:
      - 33145
    volumes:
      - ./volumes/redpanda1:/var/lib/redpanda/data

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    volumes: 
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - "redpanda1"

  grafana:
    image: grafana/grafana:7.5.10
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - "prometheus"

