global:
  scrape_interval: 15s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'redpanda'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['redpanda1:9644']


